### ISSUE TITLE
Data unavailable

### ISSUE THREAD

**Issue by jstulips** [qsjxyz/Electric-Pylon-Detection-in-RSI#1]
Hi @qsjxyz , I tried to download the data (Baidu link) but the files are no longer available. Can I request for the data to be made available again? Thanks in advance.

**Comment by robmarkcole** [comment]
Even better would be to put the data on kaggle

**Comment by thesolzen** [comment]
Hi, where could we get the dataset to run your codebase? If it is still available, please send the link to download. Thanks a lot.

**Comment by qsjxyz** [comment]
I have already put the dataset on kaggle, thank you for you advice.

**Comment by thesolzen** [comment]
I have found it. Thank you!

**Comment by jstulips** [comment]
thank you @qsjxyz this is great! 
Re-posting here for convenience: https://www.kaggle.com/qiaosijia/epd-dataset
